baseURL: 'https://nmayorov.github.io'
languageCode: 'en-us'
title: 'My Blog'
theme: 'PaperMod'

params:
  katex: true
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  author: "Nikolay Mayorov"

menu:
  main:
    - name: Archive
      title: Archive
      url: archives
    - name: Tags
      title: Tags
      url: /tags
